name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      run-benchmarks:
        description: "Run benchmark tests"
        required: false
        default: "false"
      bench-records:
        description: "Benchmark record count"
        required: false
        default: "50000"
      bench-iters:
        description: "Benchmark iterations"
        required: false
        default: "1000"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Build and test (no benchmarks)
        run: ./mvnw -B -DskipTests=false test

      - name: Build app jar
        run: ./mvnw -B -DskipTests package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}

  benchmarks:
    if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs['run-benchmarks'] == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Run benchmarks
        run: |
          ./mvnw -B -Dbench=true \
            -Dbench.records=${{ github.event.inputs['bench-records'] }} \
            -Dbench.iters=${{ github.event.inputs['bench-iters'] }} test
